all: plots
plots:
	gnuplot PLOT_Signal_Time
	gnuplot PLOT_Signal_Freq
	
	gnuplot PLOT_Sinus_Time
	gnuplot PLOT_Sinus_Freq
	gnuplot PLOT_Sinus_Clear_Time
	gnuplot PLOT_Sinus_Clear_Freq
	gnuplot PLOT_Signal_Filtered
